#!/bin/sh
# postrm for lillycoder
set -e

case "$1" in
    purge)
        # Per-project state lives in $project/.lillycoder; we don't touch
        # those. User config lives at ~/.config/lillycoder; we don't touch
        # that either since it may be needed for re-install.
        :
        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        :
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
